### ISSUE TITLE
To Resolve Permission denied: '/iesl' error 

### ISSUE THREAD

**Issue by Khyati-Microcrispr** [chanzuckerberg/ChemDisGene#3]
**Hi, thank you for such a amazing corpus taking all relations into account. while I was executing the baseline model script I got this error (pasted below). KIndly help ime resolve this.**

**error**
python src/main.py --data_path data/ --learning_rate 1e-5 --mode train --encoder_type microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract --model biaffine
output_path /iesl/canvas/dongxuzhang/ChemDisGene/baseline/saved_models/data/data_microsoft-BiomedNLP-PubMedBERT-base-uncased-abstract_biaffine_multilabel_True_lr_1e-05_dim_128_acc_16_len_512_decay_0.0001_dp_0.1_warmup_-1.0_seed_2861
Traceback (most recent call last):
  File "src/main.py", line 202, in <module>
    main()
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "src/main.py", line 172, in main
    data, model, device, logger = setup(config)
  File "/Khyati/git-lfs-3.5.1/ChemDisGene/baseline/src/module/setup.py", line 50, in setup
    os.makedirs(config["output_path"])
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/home/khyati/anaconda3/envs/chemdisgene/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/iesl'

**Comment by Khyati-Microcrispr** [comment]
It has resolved Thanks
